export const LOCALIZED_STRINGS_OBJECT = {
    it: {
        ADDRESS: "Indirizzo",
        ALBUMS: "Albums",
        BACKWARD: "Indietro",
        CANCEL: "Annulla",
        CLOSE: "Chiudi",
        COMPANY: "Azienda",
        DATE: "Data",
        DESCRIPTION: "Descrizione",
        EMAIL: "Email",
        ERROR_ACCESS_DATA: "Errore accesso ai dati",
        FORWARD: "Avanti",
        INPUT_TEXT_PLACEHOLDER: "Inserisci testo",
        LOADING: "Caricamento...",
        LOAD_COMPLETED: "Caricamento completato",
        NAME: "Nome",
        NO: "No",
        NO_RESULT: "Vuoto",
        OK: "Ok",
        PHONE: "Telefono",
        PHOTOS: "Foto",
        POSTS: "Posts",
        RESET: "Reset",
        RETRY: "Tocca per ricaricare",
        SELECT_LANGUAGE: "Cambia lingua",
        TODOS: "To-do",
        USERS: "Utenti",
        WARNING: "Attenzione",
        WEBSITE: "Website",
        YES: "Sì",
    },
    en: {
        ADDRESS: "Address",
        ALBUMS: "Albums",
        BACKWARD: "Back",
        CANCEL: "Cancel",
        CLOSE: "Close",
        COMPANY: "Company",
        DATE: "Date",
        DESCRIPTION: "Description",
        EMAIL: "Email",
        ERROR_ACCESS_DATA: "Error access data",
        FORWARD: "Forward",
        INPUT_TEXT_PLACEHOLDER: "Type some text",
        LOADING: "Loading...",
        LOAD_COMPLETED: "Loading completed",
        NAME: "Name",
        NO: "No",
        NO_RESULT: "Empty",
        OK: "Ok",
        PHONE: "Phone",
        PHOTOS: "Photos",
        POSTS: "Posts",
        RESET: "Reset",
        RETRY: "Retry",
        SELECT_LANGUAGE: "Select the language",
        TODOS: "Todos",
        USERS: "Users",
        WARNING: "Warning",
        WEBSITE: "Website",
        YES: "Yes",
    },
    de: {
        ADDRESS: "Adresse",
        ALBUMS: "Fotoalben",
        BACKWARD: "Zurück",
        CANCEL: "Abbrechen",
        CLOSE: "Schließen",
        COMPANY: "Firma",
        DATE: "Datum",
        DESCRIPTION: "Bezeichnung",
        EMAIL: "E-Mail",
        ERROR_ACCESS_DATA: "Fehler beim Datenzugriff",
        FORWARD: "Fortfahren",
        INPUT_TEXT_PLACEHOLDER: "Text eingeben",
        LOADING: "Daten werden geladen",
        LOAD_COMPLETED: "Ladevorgang abgeschlossen",
        NAME: "Name",
        NO: "Nein",
        NO_RESULT: "Leer",
        OK: "Ok",
        PHONE: "Telefon",
        PHOTOS: "Fotos",
        POSTS: "Posts",
        RESET: "Reset",
        RETRY: "Erneut versuchen",
        SELECT_LANGUAGE: "Sprache ӓndern",
        TODOS: "Todos",
        USERS: "Benutzer",
        WARNING: "Achtung",
        WEBSITE: "Website",
        YES: "Ja",
    },};
